version: "3.8"

services: 
  users-auth-api-boilerplate:
    image: nevezide44/users-auth-api-boilerplate:latest
    restart: always
    env_file:
      - .env.prod
    ports: 
      - ${API_PORT}:${API_PORT}
    depends_on: 
      - postgres:
          condition: service_healthy

  postgres:
    image: nevezide44/postgres:alpine3.17
    restart: always
    expose: 
      - 5432
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    env_file:
      - .env.prod
